application:
  title: Tic Tac Toe

window:
  width: 500
  height: 900

engine:
  targetFrameRate: 60
  showSplashScreen: false

assets:
  hotReload: true
  hotReloadDelayMilliseconds: 150

layers:
  - engine
  - game
